# SPDX-FileCopyrightText: 2025 Maximilian Franzke <mfr@nzke.net>
#
# SPDX-License-Identifier: MIT

# Configuration file for yamllint.
# It extends the default conf by adjusting some options.

extends: default

rules:
  line-length:
    max: 80
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true
  document-start:
    present: false
  document-end:
    present: false
  comments:
    min-spaces-from-content: 1
  indentation:
    spaces: 2
  trailing-spaces:
    level: error
  new-line-at-end-of-file:
    present: true
ignore: |
  .git/
  node_modules/
