name: "Revert File From Pull Request Action"
description: "Reverts a specific file in a Pull Request (PR) to the base branch version when a specific comment is posted."
author: "Maximilian Franzke"
inputs:
  github-token:
    description: "GitHub token"
    required: true
runs:
  using: "node24"
  main: "scripts/entrypoint.js"
