# SPDX-FileCopyrightText: 2025 Maximilian Franzke <mfr@nzke.net>
#
# SPDX-License-Identifier: MIT

name: Test Action

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        run: pnpm test

      # - name: Create test project with overrides
      #   env:
      #     HUSKY: 0 # Disable Husky to avoid pre-commit hooks
      #   run: |
      #     git config user.name "github-actions[bot]"
      #     git config user.email "github-actions[bot]@users.noreply.github.com"
      #     # Add lodash dependency and override to existing package.json
      #     node -e "
      #       const fs = require('node:fs');
      #       const pkg = JSON.parse(fs.readFileSync('package.json', 'utf8'));
      #       pkg.dependencies = pkg.dependencies || {};
      #       pkg.dependencies.lodash = '^4.17.20';
      #       pkg.overrides = { lodash: '^4.17.21' };
      #       fs.writeFileSync('package.json', JSON.stringify(pkg, null, 2));
      #     "
      #     git add package.json
      #     git commit -m "Add test project with overrides"

      # - name: Test action locally
      #   id: test-action
      #   uses: ./
      #   continue-on-error: true

      # - name: Verify action ran
      #   run: |
      #     echo "Action completed with exit code: ${{ steps.test-action.outcome }}"
      #     if [ -f override-removal-summary.md ]; then
      #       echo "Action produced summary:"
      #       cat override-removal-summary.md
      #     fi
      #     echo "Git status after action:"
      #     git status --porcelain || true
